--- @meta down.types.data
--- @brief Provides core data types
--- @version <5.2,JIT
---
--- @brief down.data
---
--- The important store value object
--- @class (exact) down.data.Map<K, V>: { [K]?: V } # store data
---
--- The important store value object
--- @class (exact) down.data.NestedMap<K1, K2, V>: { [K1]?: { [K2]?:  V } } # store data
---
--- The important store value object
--- @class (exact) down.data.NestedTable<K1, K2, V>: { [K1]: table<K2, V> } # store data
---
--- The important store value object
--- @class (exact) down.data.Map<K, V>: { [K]: V } # store data
---
--- The important store value object
--- @class (exact) down.data.List<K, V>: { [integer]: V } # store data
