---@meta  data.types.file
---
--- Uri is a string that represents a file path.
--- @alias down.Uri string Uri
---
---
--- The important store value object
--- @alias down.Id string
---
--- The important store value object
--- @alias down.Dir down.Uri
---
--- The important store value object
--- @alias down.File down.Uri
