--- @meta down.types
--- @brief Provides core data types
--- @version <5.2,JIT
---
---
--- The important store value object
--- @class (exact) down.old.Store<V>: { id: down.store.Name, uri: down.Uri, data?: down.store.Data<V> } store
---
--- [string]: down.Store<V>
--- @class (exact) down.old.store.Map<V>: { [down.store.Key]?: down.Store<V> } Map { log1 = { i}}
---
--- The important store value object
--- @class (exact) down.old.store.Kind: { [down.store.ItemKind]?: down.store.Map<down.store.Key> }
---
---
---
--- The scope of an entity.
--- @class (exact) down.mod.Config.Lsp  lsp
---   @field ['lsp.document']? down.lsp.document.Data lsp.document
---   @field ['lsp.workspace']? down.lsp.workspace.Data lsp.workspace
---
---   @field ['lsp.completion']? down.lsp.completion.Data lsp.completion
---
--- @class (exact) down.mod.Config
---   @field public lsp? lsp.Config
---

--- The scope of an entity.
--- @class down.mod.Mods: {
---   ui?: down.mod.ui.Config,
---   note?: down.mod.note.Config,
---   workspace?: down.mod.workspace.Config,
---   lsp?: down.mod.lsp.Config,
---   edit?: down.mod.edit.Config,
---   data?: down.mod.data.Config,
---   tool?: down.mod.tool.Config,
---   tool?: down.mod.tool.Config,
---   cmd?: down.mod.cmd.Config,
---   config?: down.mod.cmd.Config,
--- }
---
---   @field ['lsp.document']? lsp.document.Data
---   @field ['lsp.workspace']? lsp.workspace.Data
---   @field ['lsp.completion']? lsp.completion.Data
---   @field ['lsp.actions']? lsp.actions.Data
---   @field ['lsp.command']? lsp.command.Data
---   @field ['lsp.hint']? lsp.hint.Data
---   @field ['data.task']? data.task.Data
---   @field ['data.store']? data.store.Data
---   @field ['data.task.agenda']? data.task.agenda.Data
---   @field ['data.log']? data.log.Data
---   @field ['lsp.hover']? lsp.hover.Data
---   @field ['lsp.lens']? lsp.lens.Data
---   @field lsp? lsp.Data
---   @field ['lsp.window']? lsp.window.Data
---   @field ['lsp.semantic']? lsp.semantic.Data
---   @field ["edit.conceal"]? edit.conceal.Data
---   @field ["ui.icon"]? ui.icon.Data
---   @field workspace? workspace.Data
---   @field ["edit.fold"]? edit.fold.Data
---   @field ["edit.hl"]? edit.hl.Data
---   @field ["ui.win"]? ui.win.Data
---   @field note? note.Data
---   @field ['data.clipboard']? data.clipboard.Data
---   @field ['data.dirs']? data.dirs.Data
---   @field ['data.export']? data.export.Data
---   @field ['data.encrypt']? data.encrypt.Data
---   @field ['data.metadata']? data.metadata.Data
---   @field ['data.syntax']? data.syntax.Data
---   @field ['data.toc']? data.toc.Data
---   @field ['edit.parse']? edit.parse.Data
---   @field ['data.log']? data.log.Data
---   @field ['data.link']? data.link.Data
---   @field ['edit.link']? edit.link.Data
---   @field cmd? cmd.Data
---   @field ['data.tag']? data.tag.Data
---   @field ['data.sync']? data.sync.Data
---   @field ['data.mod']? data.mod.Data
---   @field ['data.code']? data.code.Data
---   @field ['data.todo']? data.todo.Data
---   @field ['edit.todo']? edit.todo.Data
---   @field ['edit.cursor']? edit.cursor.Data
---   @field ['edit.find']? down.edit.find.Data
---   @field ['edit.link']? down.edit.link.Data
---   @field ['edit.indent']? down.edit.indent.Data
---   @field ui? down.ui.Data
---   @field media? down.data.media.Data media
---   @field ['data.template']? down.data.template.Data
---   @field ["data.code.snippet"]? down.data.code.snippet.Data
---   @field ["data.code.run"]? down.data.code.run.Data
---   @field ["ui.calendar"]? down.ui.calendar.Data
---   @field ["ui.calendar.month"]? down.ui.calendar.month.Data
---   @field ["integration.treesitter"]? down.down.integration.treesitter.Data
---   @field ["integration.blink"]? down.integration.blink.Data
---   @field ["integration.cmp"]? down.integration.cmp.Data
---   @field ["integration.telescope"]? down.integration.telescope.Data
---   @field ["integration.lualine"]? down.integration.lualine.Data
---   @field ["integration.trouble"]? down.integration.trouble.Data
---   @field ["integration.fzf"]? down.integration.fzf.Data
---   @field ["ui.chat"]? down.ui.chat.Data
---   @field ["ui.sidebar"]? down.ui.sidebar.Data
---   @field ["ui.popup"]? down.ui.popup.Data
---   @field ["ui.status"]? down.ui.status.Data
---
--- down.Mods
--- @alias down.Mods down.mod.Mods
---
--- @class (exact) down.mod.config.Cfg: table
---   @field [string]? { [string]?: any }
---   @field enabled? boolean
--- @alias down.mod.Config down.mod.Modconfig.Config
---
--- TODO: merge data field to [string]? { [string]?: down.Event }
--- TODO:   down.mod.Events.defined ->
--- TODO:     #field [string]? { [string]?: down.Event }
---
--- @class (exact) down.event.Subscribed
---   @field public [string]? { [string]: boolean }

--- @class (exact) down.mod.Events
---   @field defined? { [string]: down.Event }              Lists all events by this init.
---   @field subscribed? { [string]: { [string]: boolean } } Lists the events that the init is subscribed to.
---   @field public [string]? down.Event

--- @class (exact) down.mod.Setup: {
---   [string]?: { [string]?: any },
---   loaded: boolean,
---   requires?: string[],
---   replaces?: string,
---   merge?: boolean,
---   wants?: string[] }
---   @field public [string]? any
---
--- @class (exact) down.mod.Config: { [string]?: any }
---   @field public [string]? any

--- TODO: merge data field to [string]?: down.mod.Data
--- TODO:   down.Mod.data ->
--- TODO:     #field [string]? down.config.UserMod
--- TODO:   down.Mod.config ->
--- TODO:     #field config? down.mod.Config

--- @class (exact) down.Mod
---   @field public [string]? down.mod.Data
---   @field hook? fun(arguments?: string)    A user-defined function that is invoked whenever down starts up. May be used to e.g. set custom keybindings.
---   @field config? down.mod.Config The config for the init.
---   @field events? down.mod.Events Describes all information related to events for this init.
---   @field import? table<string, down.Mod> Imported submod of the given init. Contrary to `required`, which only exposes the public API of a init, imported mod can be accessed in their entirety.
---   @field cmds? fun() Function that adds all the commands for the init.
---   @field opts? fun() Function that adds all the options for the init.
---   @field maps? fun() Function that adds all the mappings for the init.
---   @field load? fun() Function that is invoked once the init is considered "stable", i.e. after all dependencies are loaded. Perform your main loading routine here.
---   @field test? fun() Function that is invoked when the init is being tested.
---   @field version? string
---   @field bench? fun() Function that is invoked when the init is being benchmarked.
---   @field name string The name of the init.
---   @field namespace string The name of the init.
---   @field post_load? fun() Function that is invoked after all mod are loaded. Useful if you want the down environment to be fully set up before performing some task.
---   @field public data? down.mod.Data Every init can expose any set of information it sees fit through this field. All functions and variables declared in this table will be to any other init loaded.
---   @field required? table<string, down.Mod.Data> Contains the public tables of all mod that were required via the `requires` array provided in the `setup()` function of this init.
---   @field setup? fun(): down.mod.Setup? Function that is invoked before any other loading occurs. Should perform preliminary startup tasks.
---   @field replaced? boolean If `true`, this means the init is a replacement for a base init. This flag is set automatically whenever `setup().replaces` is set to a value.
---   @field on fun(event: down.Event) A callback that is invoked any time an event the init has subscribed to has fired.
---
--- @class (exact) down.config.Ft
---   @field md boolean
---   @field mdx boolean
---   @field markdown boolean
---   @field down boolean
---
--- TODO: make down.config.User? table
--- TODO:   down.config.config.User.mod.config ->
--- TODO:     #field [string]? down.config.UserMod
---
--- @class (exact) down.config.User
---   @field [string]? down.config.mod.Config
---   @field hook? fun(args?: string) Hook to optionally run on load
---   @field dev? boolean Whether to start in dev mode
---
--- TODO: make down.config.UserMod? table
--- TODO:   down.config.UserMod.config ->
--- TODO:     #field [string]? down.Mod
---
--- The entire mod configuration
--- @alias down.config.Mod
---   | down.mod.Lsp
---   | down.mod.Edit
---   | down.mod.Data
---   | down.mod.Cmd
---   | down.mod.Tool
---   | down.mod.Workspace
---   | down.mod.Note
---   | down.mod.Ui
---
--- The entire mod configuration
--- @alias down.config.mod.Config
---   | down.mod.lsp.Config
---   | down.mod.data.Config
---   | down.mod.edit.Config
---   | down.mod.config.Config
---   | down.mod.cmd.Config
---   | down.mod.tool.Config
---   | down.mod.workspace.Config
---   | down.mod.note.Config
---   | down.mod.ui.Config
---
--- @alias down.Mod.Data
---   | down.mod.lsp.Data
---   | down.mod.data.Data
---   | down.mod.edit.Data
---   | down.mod.cmd.Data
---   | down.mod.tool.Data
---   | down.mod.workspace.Data
---   | down.mod.note.Data
---   | down.mod.ui.Data
---
--- @alias down.Mod.Config
---   | down.mod.lsp.Config
---   | down.mod.data.Config
---   | down.mod.edit.Config
---   | down.mod.config.Config
---   | down.mod.cmd.Config
---   | down.mod.tool.Config
---   | down.mod.workspace.Config
---   | down.mod.note.Config
---   | down.mod.ui.Config
---
--- The base configuration
--- @class (exact) down.config.BaseConfig: {
---   [string]?: any,
---   dev?: boolean,
--- }
---
--- @class (exact) down.config.UserConfig: down.config.BaseConfig, {
---   lsp?: down.mod.lsp.Config,
---   data?: down.mod.data.Config,
---   edit?: down.mod.edit.Config,
---   config?: down.mod.config.Config,
---   cmd?: down.mod.cmd.Config,
---   tool?: down.mod.tool.Config,
---   workspace?: down.mod.worksspace.Config,
---   note?: down.mod.note.Config,
---   ui?: down.mod.ui.Config,
---   config?: down.mod.config.Config,
--- }

--- TODO: make mod field merge to [string]: down.Mod
--- TODO:   down.Config.mod ->
--- TODO:     #field [string]? down.Mod
---
--- @class (exact) down.Config
---   @field dev? boolean  Whether to start in dev mode
---   @field hook? fun()   A hook that is run when down is started
---   @field workspace? string[]
---   @field mod table<string, down.Mod> Acts as a copy of the user's config that may be modified at runtime.
---   @field os down.Os                           The operating system that down is currently running under.
---   @field pathsep "\\"|"/"                                  The operating system that down is currently running under.
---   @field started boolean                                   Set to `true` when down is fully initialized.
---   @field user down.config.User              Stores the config provided by the user.
---   @field version string                                    The version of down that is currently active. Automatically updated by CI on every release.
---   @field public [string]? down.Mod
---   @field load {
---     opts: fun(),
---     maps: fun(),
---     lsp: fun()
---   }
---   @field setup fun(user: down.config.User, ...: any): boolean Loads user config

--- Stores the config for the entirety of down.
--- This includes not only the user config (passed to `setup()`), but also internal
--- variables that describe something specific about the user's hardware.
--- @see down.Setup
---
---
--- @class (exact) down.Event
---   @field type string The type of the event. Exists in the format of `category.name`.
---   @field split string[] The event type, just split on every `.` character, e.g. `{ "category", "name" }`.
---   @field body? table|any The content of the event. The data found here is specific to each individual event. Can be thought of as the payload.
---   @field ref string The name of the init that triggered the event.
---   @field broadcast boolean Whether the event was broadcast to all mod. `true` is so, `false` if the event was specifically sent to a single recipient.
---   @field position { [1]: number, [2]: number } The position of the cursor at the moment of broadcasting the event.
---   @field file string The name of the file that the user was in at the moment of broadcasting the event.
---   @field dir string The name of the file that the user was in at the moment of broadcasting the event.
---   @field line string The content of the line the user was editing at the moment of broadcasting the event.
---   @field buf number The buffer ID of the buffer the user was in at the moment of broadcasting the event.
---   @field win number The window ID of the window the user was in at the moment of broadcasting the event.
---   @field mode Mode The mode Neovim was in at the moment of broadcasting the event.
---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
