---@meta
---
--- @alias down.mod.Data { [any]: any }

--- @class (exact) down.mod.Mods
--- @field ['lsp.document']? lsp.document.Data
--- @field ['lsp.workspace']? lsp.workspace.Data
--- @field ['lsp.completion']? lsp.completion.Data
--- @field ['lsp.actions']? lsp.actions.Data
--- @field ['lsp.command']? lsp.command.Data
--- @field ['lsp.hint']? lsp.hint.Data
--- @field ['lsp.hover']? lsp.hover.Data
--- @field ['lsp.lens']? lsp.lens.Data
--- @field lsp? lsp.Data
--- @field ['lsp.window']? lsp.window.Data
--- @field ['lsp.semantic']? lsp.semantic.Data
--- @field ["edit.conceal"]? edit.conceal.Data
--- @field ["ui.icon"]? ui.icon.Data
--- @field workspace? workspace.Data
--- @field ["edit.fold"]? edit.fold.Data
--- @field ["edit.hl"]? edit.hl.Data
--- @field ["ui.win"]? ui.win.Data
--- @field note? note.Data
--- @field ['data.clipboard']? data.clipboard.Data
--- @field ['data.dirs']? data.dirs.Data
--- @field ['data.export']? data.export.Data
--- @field ['data.encrypt']? data.encrypt.Data
--- @field ['data.metadata']? data.metadata.Data
--- @field ['data.syntax']? data.syntax.Data
--- @field ['data.toc']? data.toc.Data
--- @field ['edit.parse']? edit.parse.Data
--- @field ['data.log']? data.log.Data
--- @field ['data.link']? data.link.Data
--- @field ['edit.link']? edit.link.Data
--- @field cmd? cmd.Data
--- @field ['data.tag']? data.tag.Data
--- @field ['data.sync']? data.sync.Data
--- @field ['data.mod']? data.mod.Data
--- @field ['data.code']? data.code.Data
--- @field ['data.todo']? data.todo.Data
--- @field ['edit.todo']? edit.todo.Data
--- @field ['edit.cursor']? edit.cursor.Data
--- @field ['edit.find']? down.edit.find.Data
--- @field ['edit.link']? down.edit.link.Data
--- @field ['edit.indent']? down.edit.indent.Data
--- @field ui? down.ui.Data
--- @field ['data.template']? down.data.template.Data
--- @field ["data.code.snippet"]? down.data.code.snippet.Data
--- @field ["data.code.run"]? down.data.code.run.Data
--- @field ["ui.calendar"]? down.ui.calendar.Data
--- @field ["ui.calendar.month"]? down.ui.calendar.month.Data
--- @field ["integration.treesitter"]? down.down.integration.treesitter.Data
--- @field ["integration.blink"]? down.integration.blink.Data
--- @field ["integration.cmp"]? down.integration.cmp.Data
--- @field ["integration.telescope"]? down.integration.telescope.Data
--- @field ["integration.lualine"]? down.integration.lualine.Data
--- @field ["integration.trouble"]? down.integration.trouble.Data
--- @field ["integration.fzf"]? down.integration.fzf.Data
--- @field ["ui.chat"]? down.ui.chat.Data
--- @field ["ui.sidebar"]? down.ui.sidebar.Data
--- @field ["ui.popup"]? down.ui.popup.Data
--- @field ["ui.status"]? down.ui.status.Data
--- @field ["ui.win"]? down.ui.win.Data

--- Defines both a public and private config for a down init.
--- Public configs may be tweaked by the user from the `down.setup()` function,  whereas private configs are for internal use only.
--- @alias down.mod.Config table

--- @class (exact) down.mod.Events
--- @field defined? { [string]: down.Event }              Lists all events by this init.
--- @field subscribed? { [string]: { [string]: boolean } } Lists the events that the init is subscribed to.

--- @alias down.mod.Setup { loaded: boolean, requires?: string[], replaces?: string, merge?: boolean, wants?: string[] }

--- Defines a init.
--- A init is an object that contains a set of hooks which are invoked by down whenever something in the
--- environment occurs. This can be an event, a simple act of the init being loaded or anything else.
--- @class (exact) down.Mod
--- @field hook? fun(manual: boolean, arguments?: string)    A user-defined function that is invoked whenever down starts up. May be used to e.g. set custom keybindings.
--- @field config? down.mod.Config The config for the init.
--- @field events? down.mod.Events Describes all information related to events for this init.
--- @field import? table<string, down.Mod> Imported submod of the given init. Contrary to `required`, which only exposes the public API of a init, imported mod can be accessed in their entirety.
--- @field cmds? fun() Function that adds all the commands for the init.
--- @field opts? fun() Function that adds all the options for the init.
--- @field maps? fun() Function that adds all the mappings for the init.
--- @field load? fun() Function that is invoked once the init is considered "stable", i.e. after all dependencies are loaded. Perform your main loading routine here.
--- @field test? fun() Function that is invoked when the init is being tested.
--- @field bench? fun() Function that is invoked when the init is being benchmarked.
--- @field name string The name of the init.
--- @field namespace string The name of the init.
--- @field post_load? fun() Function that is invoked after all mod are loaded. Useful if you want the down environment to be fully set up before performing some task.
--- @field path string The full path to the init (a more verbose version of `name`). Moday be used in lua's `require()` statements.
--- @field public data? down.mod.Data Every init can expose any set of information it sees fit through this field. All functions and variables declared in this table will be to any other init loaded.
--- @field required? down.mod.Mods Contains the public tables of all mod that were required via the `requires` array provided in the `setup()` function of this init.
--- @field setup? fun(): down.mod.Setup? Function that is invoked before any other loading occurs. Should perform preliminary startup tasks.
--- @field replaced? boolean If `true`, this means the init is a replacement for a base init. This flag is set automatically whenever `setup().replaces` is set to a value.
--- @field on fun(event: down.Event) A callback that is invoked any time an event the init has subscribed to has fired.
--- Returns a new down init, exposing all the necessary function and variables.
--- @return down.Mod
---
---
--- @alias OperatingSystem
--- | "windows"
--- | "wsl"
--- | "wsl2"
--- | "mac"
--- | "linux"
--- | "bsd"
--- TODO: make down.config.UserMod? table
--- @alias down.config.UserMod { config?: table }

--- @class (exact) down.config.Ft
--- @field md boolean
--- @field mdx boolean
--- @field markdown boolean
--- @field down boolean

--- @class (exact) down.Config
--- @field args table<string, string>                   A list of arguments provided to the `:downStart` function in the form of `key=value` pairs. Only applicable when `user_config.lazy_loading` is `true`.
--- @field manual boolean?                                   Used if down was manually loaded via `:downStart`. Only applicable when `user_config.lazy_loading` is `true`.
--- @field mod table<string, down.Mod> Acts as a copy of the user's config that may be modified at runtime.
--- @field os OperatingSystem                           The operating system that down is currently running under.
--- @field pathsep "\\"|"/"                                  The operating system that down is currently running under.
--- @field started boolean                                   Set to `true` when down is fully initialized.
--- @field user down.config.User              Stores the config provided by the user.
--- @field version string                                    The version of down that is currently active. Automatically updated by CI on every release.

--- Stores the config for the entirety of down.
--- This includes not only the user config (passed to `setup()`), but also internal
--- variables that describe something specific about the user's hardware.
--- @see down.Setup
---
---
--- @alias Mode
--- | "n"
--- | "no"
--- | "nov"
--- | "noV"
--- | "noCTRL-V"
--- | "CTRL-V"
--- | "niI"
--- | "niR"
--- | "niV"
--- | "nt"
--- | "Terminal"
--- | "ntT"
--- | "v"
--- | "vs"
--- | "V"
--- | "Vs"
--- | "CTRL-V"
--- | "CTRL-Vs"
--- | "s"
--- | "S"
--- | "CTRL-S"
--- | "i"
--- | "ic"
--- | "ix"
--- | "R"
--- | "Rc"
--- | "Rx"
--- | "Rv"
--- | "Rvc"
--- | "Rvx"
--- | "c"
--- | "cr"
--- | "cv"
--- | "cvr"
--- | "r"
--- | "rm"
--- | "r?"
--- | "!"
--- | "t"

--- @class (exact) down.Event
--- @field type string The type of the event. Exists in the format of `category.name`.
--- @field split_type string[] The event type, just split on every `.` character, e.g. `{ "category", "name" }`.
--- @field content? table|any The content of the event. The data found here is specific to each individual event. Can be thought of as the payload.
--- @field referrer string The name of the init that triggered the event.
--- @field broadcast boolean Whether the event was broadcast to all mod. `true` is so, `false` if the event was specifically sent to a single recipient.
--- @field cursor_position { [1]: number, [2]: number } The position of the cursor at the moment of broadcasting the event.
--- @field filename string The name of the file that the user was in at the moment of broadcasting the event.
--- @field filehead string The directory the user was in at the moment of broadcasting the event.
--- @field line_content string The content of the line the user was editing at the moment of broadcasting the event.
--- @field buffer number The buffer ID of the buffer the user was in at the moment of broadcasting the event.
--- @field window number The window ID of the window the user was in at the moment of broadcasting the event.
--- @field mode Mode The mode Neovim was in at the moment of broadcasting the event.
---
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
---
--- @brief down
--- @see down
---
